openapi: 3.0.0
info:
  title: Job Description Processing API
  description: API for processing and extracting job descriptions from uploaded files
  version: 1.0.0
  contact:
    name: API Support
    email: support@recruitgenius.com

servers:
  - url: http://localhost:8000/api/v1
    description: Development server

paths:
  /job-description/process:
    post:
      summary: Process job description file
      description: Upload and process a job description file (PDF, DOC, DOCX) to extract formatted text
      tags:
        - Job Description
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: Job description file to process (PDF, DOC, DOCX)
              required:
                - file
      responses:
        '200':
          description: File processed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobDescriptionResponse'
        '400':
          description: Bad request - Invalid file type or missing file
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '413':
          description: File too large
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /job-description/generate:
    post:
      summary: Generate job description with AI
      description: Generate a comprehensive job description using AI based on provided parameters
      tags:
        - Job Description
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobDescriptionGenerateRequest'
      responses:
        '200':
          description: Job description generated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobDescriptionResponse'
        '400':
          description: Bad request - Invalid parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    JobDescriptionResponse:
      type: object
      properties:
        formatted_text:
          type: string
          description: The extracted and formatted job description text
          example: |
            **Job Title:** Senior Python Developer
            
            **Company:** Tech Corp
            
            **Department:** Engineering
            
            **Job Summary:**
            Tech Corp is seeking a highly motivated and experienced Senior Python Developer to join our dynamic engineering team...
        processing_time:
          type: number
          format: float
          description: Time taken to process the file in seconds
          example: 5.23
      required:
        - formatted_text
        - processing_time

    JobDescriptionGenerateRequest:
      type: object
      properties:
        job_title:
          type: string
          description: The job title for the position
          example: "Senior Python Developer"
        experience:
          type: string
          description: Required experience level
          example: "3-5 years"
        company:
          type: string
          description: Company name
          example: "Tech Corp"
        job_type:
          type: string
          description: Type of employment
          example: "Full-time"
        must_have_skills:
          type: string
          description: Required skills for the position
          example: "Python, FastAPI, React, TypeScript, Node.js"
        industry:
          type: string
          description: Industry sector
          example: "Technology"
        location:
          type: string
          description: Job location
          example: "San Francisco, CA"
      required:
        - job_title
        - experience
        - company
        - job_type
        - must_have_skills
        - industry
        - location
    
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Error message
          example: "Invalid file type. Please upload PDF, DOC, or DOCX files only."
        status:
          type: integer
          description: HTTP status code
          example: 400
      required:
        - message

tags:
  - name: Job Description
    description: Operations related to job description processing and generation 