openapi: 3.0.0
info:
  title: Job Description Processing API
  description: API for processing and extracting job descriptions from uploaded files
  version: 1.0.0
  contact:
    name: API Support
    email: support@recruitgenius.com

servers:
  - url: http://localhost:8000/api/v1
    description: Development server

paths:
  /job-description/process:
    post:
      summary: Process job description file
      description: Upload and process a job description file (PDF, DOC, DOCX) to extract formatted text
      tags:
        - Job Description
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: Job description file to process (PDF, DOC, DOCX)
              required:
                - file
      responses:
        '200':
          description: File processed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  formatted_text:
                    type: string
                    description: The extracted and formatted job description text
                    example: |
                      **Job Title:** Associate Brand Manager
                      
                      **Company/Department:** ABC (a division of Sample Corporation)
                      
                      **Job Summary:**
                      As an Associate Brand Manager you will be working for ABC division for brands such as X, Y, Z, etc.
                  processing_time:
                    type: number
                    format: float
                    description: Time taken to process the file in seconds
                    example: 3.84
        '400':
          description: Bad request - Invalid file type or missing file
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid file type. Please upload PDF, DOC, or DOCX files only."
        '413':
          description: File too large
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "File size exceeds maximum allowed limit of 10MB."
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Failed to process the file. Please try again."

components:
  schemas:
    JobDescriptionResponse:
      type: object
      properties:
        formatted_text:
          type: string
          description: The extracted and formatted job description text
        processing_time:
          type: number
          format: float
          description: Time taken to process the file in seconds
      required:
        - formatted_text
        - processing_time
    
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Error message
        status:
          type: integer
          description: HTTP status code
      required:
        - message

tags:
  - name: Job Description
    description: Operations related to job description processing 